inertial_frame_id: world
waypoints:
  -
    point: [0., 0., -50.]
    max_forward_speed: 0.4
    heading: 0.
    use_fixed_heading: True
  -
    point: [12., 0., -50.]
    max_forward_speed: 0.4
    heading: 0.7853982
    use_fixed_heading: True
  -
    point: [12., 0., -41.]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: True
  -
    point: [0., 0., -50.]
    max_forward_speed: 0.4
    heading: 3.14
    use_fixed_heading: True